Artificial Intelligence SmartBridge Externship Assesment - 1

Create a pandas datafram (DataFram name as 'df') with numpy random values(*4* features and 4 observations)

In [ ]:
# 1. Create a pandas dataframe('df') with numpy random values (4 features and 4 obs)

import pandas as pd
import numpy as np

o1 = pd.Series(np.random.rand(4))
o2 = pd.Series(np.random.rand(4))
o3 = pd.Series(np.random.rand(4))
o4 = pd.Series(np.random.rand(4))

df = pd.DataFrame([o1, o2, o3, o4])
# print(df)
df

          0         1         2         3
0  0.922790  0.515824  0.660518  0.597972
1  0.030346  0.354511  0.624106  0.098043
2  0.045839  0.637987  0.083994  0.429320
3  0.828282  0.523106  0.829353  0.868222

In [ ]:
# 2. Rename the task-1 'df' dataframe columns to Random value 1, Random value 2, Random value 3, Random value 4

df.columns = ['Random value 1',   'Random value 2', 'Random value 3', 'Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.724460        0.319865        0.286128        0.357202
1        0.652410        0.057300        0.001066        0.693164
2        0.159152        0.774220        0.263640        0.310405
3        0.977440        0.428120        0.896603        0.061488

In [ ]:
## 3. Find the desciptive statistics of the 'df' dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.628365        0.394876        0.361859        0.355565
std          0.342455        0.296980        0.379256        0.259805
min          0.159152        0.057300        0.001066        0.061488
25%          0.529095        0.254224        0.197997        0.248176
50%          0.688435        0.373992        0.274884        0.333804
75%          0.787705        0.514645        0.438747        0.441192
max          0.977440        0.774220        0.896603        0.693164

In [ ]:
# ## 4. Check the null values in 'df' and find the datatype of the columns

print(df.isnull(),"\n")
print(df.dtypes)

# df.isnull(),"\n"
# df.dtypes

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
# ## 5. Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

# print(df.iloc[:,[1,2]])
df.iloc[:,[1,2]]

   Random value 2  Random value 3
0        0.319865        0.286128
1        0.057300        0.001066
2        0.774220        0.263640
3        0.428120        0.896603

In [ ]:
# print(df.loc[:,["Random value 2", "Random value 3"]])
# print(df.loc[:,[1,2]])
df.loc[:,[1,2]]

          1         2
0  0.515824  0.660518
1  0.354511  0.624106
2  0.637987  0.083994
3  0.523106  0.829353